"""password change tracking

Revision ID: 0b539114eb7f
Revises: c275ae0b1c03
Create Date: 2026-08-25 16:21:38.106703
"""
from alembic import op
import sqlalchemy as sa


revision = '0b539114eb7f'
down_revision = 'c275ae0b1c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add as nullable with a default of "now" for existing rows, then make
    # it NOT NULL. A straight NOT NULL add would fail on any users table
    # that already has rows (every real deployment past the first launch).
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET password_changed_at = created_at WHERE password_changed_at IS NULL")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password_changed_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    # ### end Alembic commands ###
