"""product management extensions

Revision ID: 30f139a6e22b
Revises: 7f3a1c9e5b2d
Create Date: 2026-08-28 20:13:53.942637
"""
from alembic import op
import sqlalchemy as sa


revision = '30f139a6e22b'
down_revision = '7f3a1c9e5b2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_certifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuing_organization', sa.String(length=255), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_records.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('source_evidence', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_id', sa.String(length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_crops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('crop_category', sa.String(length=100), nullable=True),
    sa.Column('target_use', sa.String(length=255), nullable=True),
    sa.Column('application_stage', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('media_id', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=32), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_records.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_pack_sizes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('packaging_type', sa.String(length=60), nullable=True),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('active_ingredients', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('nutrient_content', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('concentration', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('formulation', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('grade', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('physical_form', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('technical_specifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'technical_specifications')
    op.drop_column('products', 'physical_form')
    op.drop_column('products', 'grade')
    op.drop_column('products', 'formulation')
    op.drop_column('products', 'concentration')
    op.drop_column('products', 'nutrient_content')
    op.drop_column('products', 'active_ingredients')
    op.drop_table('product_pack_sizes')
    op.drop_table('product_documents')
    op.drop_table('product_crops')
    op.drop_table('product_claims')
    op.drop_table('product_certifications')
    # ### end Alembic commands ###
