"""Add covering indexes for foreign key columns

Revision ID: 4d2f6a8b1c93
Revises: 7b1a5e3d9c42
Create Date: 2026-09-11 21:15:00.000000

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d2f6a8b1c93"
down_revision = "7b1a5e3d9c42"
branch_labels = None
depends_on = None


# Supabase's linter flagged 93 foreign key columns across the site-content
# tables (research/manufacturing/leadership/certifications/etc.) and the
# core app tables with no covering index - every one of these is joined on
# in an admin listing or staff dashboard query, so an unindexed FK there
# means a sequential scan as those tables grow. Purely additive: no schema
# shape changes, safe to run against the live database.
def upgrade() -> None:
    op.create_index("ix_agriculture_photos_approved_by_id", "agriculture_photos", ["approved_by_id"], unique=False)
    op.create_index("ix_agriculture_photos_media_id", "agriculture_photos", ["media_id"], unique=False)
    op.create_index("ix_agriculture_photos_published_by_id", "agriculture_photos", ["published_by_id"], unique=False)
    op.create_index("ix_agriculture_photos_reviewed_by_id", "agriculture_photos", ["reviewed_by_id"], unique=False)
    op.create_index("ix_agriculture_photos_submitted_by_id", "agriculture_photos", ["submitted_by_id"], unique=False)
    op.create_index("ix_agriculture_photos_uploaded_by_id", "agriculture_photos", ["uploaded_by_id"], unique=False)
    op.create_index("ix_announcements_created_by_id", "announcements", ["created_by_id"], unique=False)
    op.create_index("ix_audit_logs_actor_id", "audit_logs", ["actor_id"], unique=False)
    op.create_index("ix_case_messages_author_id", "case_messages", ["author_id"], unique=False)
    op.create_index("ix_case_messages_case_id", "case_messages", ["case_id"], unique=False)
    op.create_index("ix_certifications_approved_by_id", "certifications", ["approved_by_id"], unique=False)
    op.create_index("ix_certifications_created_by_id", "certifications", ["created_by_id"], unique=False)
    op.create_index("ix_certifications_document_media_id", "certifications", ["document_media_id"], unique=False)
    op.create_index("ix_certifications_published_by_id", "certifications", ["published_by_id"], unique=False)
    op.create_index("ix_certifications_reviewer_id", "certifications", ["reviewer_id"], unique=False)
    op.create_index("ix_certifications_submitted_by_id", "certifications", ["submitted_by_id"], unique=False)
    op.create_index("ix_certifications_updated_by_id", "certifications", ["updated_by_id"], unique=False)
    op.create_index("ix_company_documents_approved_by_id", "company_documents", ["approved_by_id"], unique=False)
    op.create_index("ix_company_documents_media_id", "company_documents", ["media_id"], unique=False)
    op.create_index("ix_company_documents_published_by_id", "company_documents", ["published_by_id"], unique=False)
    op.create_index("ix_company_documents_reviewed_by_id", "company_documents", ["reviewed_by_id"], unique=False)
    op.create_index("ix_company_documents_submitted_by_id", "company_documents", ["submitted_by_id"], unique=False)
    op.create_index("ix_company_documents_uploaded_by_id", "company_documents", ["uploaded_by_id"], unique=False)
    op.create_index("ix_company_page_contents_approved_by_id", "company_page_contents", ["approved_by_id"], unique=False)
    op.create_index("ix_company_page_contents_created_by_id", "company_page_contents", ["created_by_id"], unique=False)
    op.create_index("ix_company_page_contents_published_by_id", "company_page_contents", ["published_by_id"], unique=False)
    op.create_index("ix_company_page_contents_reviewer_id", "company_page_contents", ["reviewer_id"], unique=False)
    op.create_index("ix_company_page_contents_submitted_by_id", "company_page_contents", ["submitted_by_id"], unique=False)
    op.create_index("ix_company_page_contents_updated_by_id", "company_page_contents", ["updated_by_id"], unique=False)
    op.create_index("ix_company_settings_updated_by_id", "company_settings", ["updated_by_id"], unique=False)
    op.create_index("ix_dealer_applications_reviewer_id", "dealer_applications", ["reviewer_id"], unique=False)
    op.create_index("ix_dealer_product_availability_product_id", "dealer_product_availability", ["product_id"], unique=False)
    op.create_index("ix_dealer_profiles_application_id", "dealer_profiles", ["application_id"], unique=False)
    op.create_index("ix_distributor_applications_reviewer_id", "distributor_applications", ["reviewer_id"], unique=False)
    op.create_index("ix_distributor_profiles_application_id", "distributor_profiles", ["application_id"], unique=False)
    op.create_index("ix_distributor_stock_product_id", "distributor_stock", ["product_id"], unique=False)
    op.create_index("ix_enquiries_assigned_staff_id", "enquiries", ["assigned_staff_id"], unique=False)
    op.create_index("ix_enquiries_product_id", "enquiries", ["product_id"], unique=False)
    op.create_index("ix_farmer_support_cases_assigned_dealer_id", "farmer_support_cases", ["assigned_dealer_id"], unique=False)
    op.create_index("ix_farmer_support_cases_assigned_field_officer_id", "farmer_support_cases", ["assigned_field_officer_id"], unique=False)
    op.create_index("ix_farmer_support_cases_assigned_staff_id", "farmer_support_cases", ["assigned_staff_id"], unique=False)
    op.create_index("ix_farmer_support_cases_farmer_id", "farmer_support_cases", ["farmer_id"], unique=False)
    op.create_index("ix_field_visits_assigned_officer_id", "field_visits", ["assigned_officer_id"], unique=False)
    op.create_index("ix_field_visits_case_id", "field_visits", ["case_id"], unique=False)
    op.create_index("ix_field_visits_farmer_id", "field_visits", ["farmer_id"], unique=False)
    op.create_index("ix_follow_up_tasks_assigned_user_id", "follow_up_tasks", ["assigned_user_id"], unique=False)
    op.create_index("ix_follow_up_tasks_created_by_id", "follow_up_tasks", ["created_by_id"], unique=False)
    op.create_index("ix_knowledge_articles_author_id", "knowledge_articles", ["author_id"], unique=False)
    op.create_index("ix_knowledge_articles_reviewer_id", "knowledge_articles", ["reviewer_id"], unique=False)
    op.create_index("ix_leadership_profiles_approved_by_id", "leadership_profiles", ["approved_by_id"], unique=False)
    op.create_index("ix_leadership_profiles_created_by_id", "leadership_profiles", ["created_by_id"], unique=False)
    op.create_index("ix_leadership_profiles_photo_media_id", "leadership_profiles", ["photo_media_id"], unique=False)
    op.create_index("ix_leadership_profiles_published_by_id", "leadership_profiles", ["published_by_id"], unique=False)
    op.create_index("ix_leadership_profiles_reviewer_id", "leadership_profiles", ["reviewer_id"], unique=False)
    op.create_index("ix_leadership_profiles_submitted_by_id", "leadership_profiles", ["submitted_by_id"], unique=False)
    op.create_index("ix_leadership_profiles_updated_by_id", "leadership_profiles", ["updated_by_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_approved_by_id", "manufacturing_facilities", ["approved_by_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_created_by_id", "manufacturing_facilities", ["created_by_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_published_by_id", "manufacturing_facilities", ["published_by_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_reviewer_id", "manufacturing_facilities", ["reviewer_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_submitted_by_id", "manufacturing_facilities", ["submitted_by_id"], unique=False)
    op.create_index("ix_manufacturing_facilities_updated_by_id", "manufacturing_facilities", ["updated_by_id"], unique=False)
    op.create_index("ix_media_records_uploaded_by_id", "media_records", ["uploaded_by_id"], unique=False)
    op.create_index("ix_password_reset_tokens_user_id", "password_reset_tokens", ["user_id"], unique=False)
    op.create_index("ix_product_categories_parent_id", "product_categories", ["parent_id"], unique=False)
    op.create_index("ix_product_images_product_id", "product_images", ["product_id"], unique=False)
    op.create_index("ix_product_reviews_moderator_id", "product_reviews", ["moderator_id"], unique=False)
    op.create_index("ix_product_reviews_product_id", "product_reviews", ["product_id"], unique=False)
    op.create_index("ix_product_reviews_user_id", "product_reviews", ["user_id"], unique=False)
    op.create_index("ix_products_category_id", "products", ["category_id"], unique=False)
    op.create_index("ix_products_created_by_id", "products", ["created_by_id"], unique=False)
    op.create_index("ix_products_reviewer_id", "products", ["reviewer_id"], unique=False)
    op.create_index("ix_products_updated_by_id", "products", ["updated_by_id"], unique=False)
    op.create_index("ix_research_areas_approved_by_id", "research_areas", ["approved_by_id"], unique=False)
    op.create_index("ix_research_areas_created_by_id", "research_areas", ["created_by_id"], unique=False)
    op.create_index("ix_research_areas_image_media_id", "research_areas", ["image_media_id"], unique=False)
    op.create_index("ix_research_areas_published_by_id", "research_areas", ["published_by_id"], unique=False)
    op.create_index("ix_research_areas_reviewer_id", "research_areas", ["reviewer_id"], unique=False)
    op.create_index("ix_research_areas_submitted_by_id", "research_areas", ["submitted_by_id"], unique=False)
    op.create_index("ix_research_areas_updated_by_id", "research_areas", ["updated_by_id"], unique=False)
    op.create_index("ix_research_facilities_approved_by_id", "research_facilities", ["approved_by_id"], unique=False)
    op.create_index("ix_research_facilities_created_by_id", "research_facilities", ["created_by_id"], unique=False)
    op.create_index("ix_research_facilities_published_by_id", "research_facilities", ["published_by_id"], unique=False)
    op.create_index("ix_research_facilities_reviewer_id", "research_facilities", ["reviewer_id"], unique=False)
    op.create_index("ix_research_facilities_submitted_by_id", "research_facilities", ["submitted_by_id"], unique=False)
    op.create_index("ix_research_facilities_updated_by_id", "research_facilities", ["updated_by_id"], unique=False)
    op.create_index("ix_staff_applications_reviewer_id", "staff_applications", ["reviewer_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_approved_by_id", "sustainability_initiatives", ["approved_by_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_created_by_id", "sustainability_initiatives", ["created_by_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_published_by_id", "sustainability_initiatives", ["published_by_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_reviewer_id", "sustainability_initiatives", ["reviewer_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_submitted_by_id", "sustainability_initiatives", ["submitted_by_id"], unique=False)
    op.create_index("ix_sustainability_initiatives_updated_by_id", "sustainability_initiatives", ["updated_by_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_agriculture_photos_approved_by_id", table_name="agriculture_photos")
    op.drop_index("ix_agriculture_photos_media_id", table_name="agriculture_photos")
    op.drop_index("ix_agriculture_photos_published_by_id", table_name="agriculture_photos")
    op.drop_index("ix_agriculture_photos_reviewed_by_id", table_name="agriculture_photos")
    op.drop_index("ix_agriculture_photos_submitted_by_id", table_name="agriculture_photos")
    op.drop_index("ix_agriculture_photos_uploaded_by_id", table_name="agriculture_photos")
    op.drop_index("ix_announcements_created_by_id", table_name="announcements")
    op.drop_index("ix_audit_logs_actor_id", table_name="audit_logs")
    op.drop_index("ix_case_messages_author_id", table_name="case_messages")
    op.drop_index("ix_case_messages_case_id", table_name="case_messages")
    op.drop_index("ix_certifications_approved_by_id", table_name="certifications")
    op.drop_index("ix_certifications_created_by_id", table_name="certifications")
    op.drop_index("ix_certifications_document_media_id", table_name="certifications")
    op.drop_index("ix_certifications_published_by_id", table_name="certifications")
    op.drop_index("ix_certifications_reviewer_id", table_name="certifications")
    op.drop_index("ix_certifications_submitted_by_id", table_name="certifications")
    op.drop_index("ix_certifications_updated_by_id", table_name="certifications")
    op.drop_index("ix_company_documents_approved_by_id", table_name="company_documents")
    op.drop_index("ix_company_documents_media_id", table_name="company_documents")
    op.drop_index("ix_company_documents_published_by_id", table_name="company_documents")
    op.drop_index("ix_company_documents_reviewed_by_id", table_name="company_documents")
    op.drop_index("ix_company_documents_submitted_by_id", table_name="company_documents")
    op.drop_index("ix_company_documents_uploaded_by_id", table_name="company_documents")
    op.drop_index("ix_company_page_contents_approved_by_id", table_name="company_page_contents")
    op.drop_index("ix_company_page_contents_created_by_id", table_name="company_page_contents")
    op.drop_index("ix_company_page_contents_published_by_id", table_name="company_page_contents")
    op.drop_index("ix_company_page_contents_reviewer_id", table_name="company_page_contents")
    op.drop_index("ix_company_page_contents_submitted_by_id", table_name="company_page_contents")
    op.drop_index("ix_company_page_contents_updated_by_id", table_name="company_page_contents")
    op.drop_index("ix_company_settings_updated_by_id", table_name="company_settings")
    op.drop_index("ix_dealer_applications_reviewer_id", table_name="dealer_applications")
    op.drop_index("ix_dealer_product_availability_product_id", table_name="dealer_product_availability")
    op.drop_index("ix_dealer_profiles_application_id", table_name="dealer_profiles")
    op.drop_index("ix_distributor_applications_reviewer_id", table_name="distributor_applications")
    op.drop_index("ix_distributor_profiles_application_id", table_name="distributor_profiles")
    op.drop_index("ix_distributor_stock_product_id", table_name="distributor_stock")
    op.drop_index("ix_enquiries_assigned_staff_id", table_name="enquiries")
    op.drop_index("ix_enquiries_product_id", table_name="enquiries")
    op.drop_index("ix_farmer_support_cases_assigned_dealer_id", table_name="farmer_support_cases")
    op.drop_index("ix_farmer_support_cases_assigned_field_officer_id", table_name="farmer_support_cases")
    op.drop_index("ix_farmer_support_cases_assigned_staff_id", table_name="farmer_support_cases")
    op.drop_index("ix_farmer_support_cases_farmer_id", table_name="farmer_support_cases")
    op.drop_index("ix_field_visits_assigned_officer_id", table_name="field_visits")
    op.drop_index("ix_field_visits_case_id", table_name="field_visits")
    op.drop_index("ix_field_visits_farmer_id", table_name="field_visits")
    op.drop_index("ix_follow_up_tasks_assigned_user_id", table_name="follow_up_tasks")
    op.drop_index("ix_follow_up_tasks_created_by_id", table_name="follow_up_tasks")
    op.drop_index("ix_knowledge_articles_author_id", table_name="knowledge_articles")
    op.drop_index("ix_knowledge_articles_reviewer_id", table_name="knowledge_articles")
    op.drop_index("ix_leadership_profiles_approved_by_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_created_by_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_photo_media_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_published_by_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_reviewer_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_submitted_by_id", table_name="leadership_profiles")
    op.drop_index("ix_leadership_profiles_updated_by_id", table_name="leadership_profiles")
    op.drop_index("ix_manufacturing_facilities_approved_by_id", table_name="manufacturing_facilities")
    op.drop_index("ix_manufacturing_facilities_created_by_id", table_name="manufacturing_facilities")
    op.drop_index("ix_manufacturing_facilities_published_by_id", table_name="manufacturing_facilities")
    op.drop_index("ix_manufacturing_facilities_reviewer_id", table_name="manufacturing_facilities")
    op.drop_index("ix_manufacturing_facilities_submitted_by_id", table_name="manufacturing_facilities")
    op.drop_index("ix_manufacturing_facilities_updated_by_id", table_name="manufacturing_facilities")
    op.drop_index("ix_media_records_uploaded_by_id", table_name="media_records")
    op.drop_index("ix_password_reset_tokens_user_id", table_name="password_reset_tokens")
    op.drop_index("ix_product_categories_parent_id", table_name="product_categories")
    op.drop_index("ix_product_images_product_id", table_name="product_images")
    op.drop_index("ix_product_reviews_moderator_id", table_name="product_reviews")
    op.drop_index("ix_product_reviews_product_id", table_name="product_reviews")
    op.drop_index("ix_product_reviews_user_id", table_name="product_reviews")
    op.drop_index("ix_products_category_id", table_name="products")
    op.drop_index("ix_products_created_by_id", table_name="products")
    op.drop_index("ix_products_reviewer_id", table_name="products")
    op.drop_index("ix_products_updated_by_id", table_name="products")
    op.drop_index("ix_research_areas_approved_by_id", table_name="research_areas")
    op.drop_index("ix_research_areas_created_by_id", table_name="research_areas")
    op.drop_index("ix_research_areas_image_media_id", table_name="research_areas")
    op.drop_index("ix_research_areas_published_by_id", table_name="research_areas")
    op.drop_index("ix_research_areas_reviewer_id", table_name="research_areas")
    op.drop_index("ix_research_areas_submitted_by_id", table_name="research_areas")
    op.drop_index("ix_research_areas_updated_by_id", table_name="research_areas")
    op.drop_index("ix_research_facilities_approved_by_id", table_name="research_facilities")
    op.drop_index("ix_research_facilities_created_by_id", table_name="research_facilities")
    op.drop_index("ix_research_facilities_published_by_id", table_name="research_facilities")
    op.drop_index("ix_research_facilities_reviewer_id", table_name="research_facilities")
    op.drop_index("ix_research_facilities_submitted_by_id", table_name="research_facilities")
    op.drop_index("ix_research_facilities_updated_by_id", table_name="research_facilities")
    op.drop_index("ix_staff_applications_reviewer_id", table_name="staff_applications")
    op.drop_index("ix_sustainability_initiatives_approved_by_id", table_name="sustainability_initiatives")
    op.drop_index("ix_sustainability_initiatives_created_by_id", table_name="sustainability_initiatives")
    op.drop_index("ix_sustainability_initiatives_published_by_id", table_name="sustainability_initiatives")
    op.drop_index("ix_sustainability_initiatives_reviewer_id", table_name="sustainability_initiatives")
    op.drop_index("ix_sustainability_initiatives_submitted_by_id", table_name="sustainability_initiatives")
    op.drop_index("ix_sustainability_initiatives_updated_by_id", table_name="sustainability_initiatives")
