"""media record entity linkage

Revision ID: c275ae0b1c03
Revises: d00d31a9b7e6
Create Date: 2026-08-25 16:11:57.633599
"""
from alembic import op
import sqlalchemy as sa


revision = 'c275ae0b1c03'
down_revision = 'd00d31a9b7e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_records', sa.Column('purpose', sa.String(length=30), nullable=False))
    op.add_column('media_records', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('media_records', sa.Column('entity_id', sa.String(length=32), nullable=True))
    op.add_column('media_records', sa.Column('alt_text', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_media_records_entity_id'), 'media_records', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_records_entity_id'), table_name='media_records')
    op.drop_column('media_records', 'alt_text')
    op.drop_column('media_records', 'entity_id')
    op.drop_column('media_records', 'entity_type')
    op.drop_column('media_records', 'purpose')
    # ### end Alembic commands ###
