"""Role and permission constants shared across the backend."""

ROLE_SUPER_ADMIN = "super_admin"
ROLE_ADMIN = "admin"
ROLE_CONTENT_MANAGER = "content_manager"
ROLE_SALES_MANAGER = "sales_manager"
ROLE_FIELD_OFFICER = "field_officer"
ROLE_DEALER = "dealer"
ROLE_DISTRIBUTOR = "distributor"
ROLE_FARMER = "farmer"

STAFF_ROLES = {
    ROLE_SUPER_ADMIN,
    ROLE_ADMIN,
    ROLE_CONTENT_MANAGER,
    ROLE_SALES_MANAGER,
    ROLE_FIELD_OFFICER,
}

PRODUCT_MANAGERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_CONTENT_MANAGER}
DEALER_MANAGERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_SALES_MANAGER}
DISTRIBUTOR_MANAGERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_SALES_MANAGER}
CASE_MANAGERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_SALES_MANAGER, ROLE_FIELD_OFFICER}
REVIEW_MODERATORS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_CONTENT_MANAGER}
SETTINGS_MANAGERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN}
# Company certificates/documents and the agriculture photo gallery are
# content, not commercial-relationship data, so they follow the same
# reviewer set as product content.
CONTENT_VERIFIERS = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_CONTENT_MANAGER}
